"""empty message

Revision ID: 658a82337d9b
Revises: e88adb39c5f6
Create Date: 2026-07-29 15:36:04.408447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '658a82337d9b'
down_revision: Union[str, Sequence[str], None] = 'e88adb39c5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('authors', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('authors', sa.Column('citizenship', sa.String(length=150), nullable=True))
    op.alter_column('authors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('books', sa.Column('description', sa.String(length=1000), nullable=False))
    op.add_column('books', sa.Column('genre', sa.ARRAY(sa.String(length=150)), nullable=True))
    op.add_column('books', sa.Column('date_written', sa.Date(), nullable=False))
    op.alter_column('books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('capitals', sa.Column('mayor', sa.String(length=100), nullable=True))
    op.add_column('capitals', sa.Column('population', sa.BigInteger(), nullable=False))
    op.alter_column('capitals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('countries', sa.Column('president', sa.String(length=100), nullable=False))
    op.add_column('countries', sa.Column('population', sa.BigInteger(), nullable=False))
    op.add_column('countries', sa.Column('currency', sa.String(length=100), nullable=True))
    op.alter_column('countries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('courses', sa.Column('description', sa.String(length=1000), nullable=False))
    op.add_column('courses', sa.Column('mentor', sa.String(length=150), nullable=False))
    op.add_column('courses', sa.Column('teaching_hours', sa.Integer(), nullable=True))
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('dormitory', sa.String(length=150), nullable=True))
    op.add_column('students', sa.Column('citizenship', sa.String(length=150), nullable=False))
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('students', 'citizenship')
    op.drop_column('students', 'dormitory')
    op.drop_column('students', 'age')
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('courses', 'teaching_hours')
    op.drop_column('courses', 'mentor')
    op.drop_column('courses', 'description')
    op.alter_column('countries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('countries', 'currency')
    op.drop_column('countries', 'population')
    op.drop_column('countries', 'president')
    op.alter_column('capitals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('capitals', 'population')
    op.drop_column('capitals', 'mayor')
    op.alter_column('books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('books', 'date_written')
    op.drop_column('books', 'genre')
    op.drop_column('books', 'description')
    op.alter_column('authors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('authors', 'citizenship')
    op.drop_column('authors', 'location')
    op.drop_column('authors', 'age')
    # ### end Alembic commands ###
